admin:
  profile_path: /dev/null
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 15000

static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        # address: "::"
        port_value: 8080
    listener_filters:
    - name: envoy.filters.listener.accept_control
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.listener.accept_control.v3.AcceptControl
        stat_prefix: accept_control
        action: ALLOW
        ip_list:
        - address_prefix: 127.0.0.1
          prefix_len: 32
        - address_prefix: "::1"
          prefix_len: 64
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          strip_any_host_port: true
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: test
            virtual_hosts:
            - name: local
              domains: 
              - "*"
              routes:
              - name: httpbin
                match:
                  prefix: "/"
                route:
                  cluster: httpbin
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: httpbin
    connect_timeout: 600s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: httpbin
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: www.httpbin.org
                    port_value: 80